from setuptools import setup, find_packages

setup(
    name='SPARSA-LM',
    fullname='Sparse Attention Lumina Language Model',
    version='0.1',
    packages=find_packages(),
    install_requires=[
        'torch',
        'torchvision',
        'torchaudio',
        'tokenizers',
        'datasets',
        'numpy',
        'scikit-learn',
        'matplotlib',
        'tqdm',
        'pyyaml',
        'pinecone-client',
        'fsspec',
        'gcsfs',
        'spacy',
        'Unidecode',
        'python-dotenv',
        'nltk',
        'rouge-score',
        'watchdog',
        'wandb',
        'tensorboard',
        'aiofiles',
        'chardet',
        'pynvml',
        'pytorch-lightning',

    ],
    author="Archit Sood @ EllanorAI",
    author_email="architsood@ellanorai.org",
    description="This is a Base LM package for Lumina",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/Archit03/LuminaLM-base-0.1",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Proprietary License",
        "Operating System :: OS Independent",
    ],
)
