datasets:

- name: local
  type: local
  config:
    path: "C:/Users/ASUS/Desktop/PreProcessed"
    patterns: 
      - "*.txt"
      - "*.csv"
    csv_text_column: "text" 

- name: medical_textbook
  type: huggingface
  config:
    dataset_name: "zxvix/MedicalTextbook"
    config_name: "Anatomy_Gray"
    cache_dir: "cache/medical"

- name: openwebtext
  type: huggingface
  config:
    dataset_name: "stas/openwebtext-10k"
    cache_dir: "cache/openwebtext" 

- name: hari560
  type: huggingface
  config:
    dataset_name: "hari560/medical-data"
    cache_dir: "cache/hari560" 

